stages:
  - build
  - image

build_artifact:
  stage: build
  image: node
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - frontend/dist/*

build_image:
  stage: image
  dependencies:
    - build_artifact
  image: docker:26.1.0
  services:
    - docker:26.1.0-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_TAG: travelbuddy:$CI_COMMIT_SHORT_SHA
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
    - docker build -t registry.gitlab.com/ccg-2/travelbuddy/$IMAGE_TAG .
    - docker push registry.gitlab.com/ccg-2/travelbuddy/$IMAGE_TAG

build_image_arm64:
  stage: image
  dependencies:
    - build_artifact
  image: docker:26.1.0
  services:
    - docker:26.1.0-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_TAG: travelbuddy:$CI_COMMIT_SHORT_SHA-arm64
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
    - docker build --platform linux/arm64/v8 -t registry.gitlab.com/ccg-2/travelbuddy/$IMAGE_TAG .
    - docker push registry.gitlab.com/ccg-2/travelbuddy/$IMAGE_TAG
