stages:
  - build
  - image

build_artifact:
  stage: build
  image: node
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - frontend/dist/*

build_image:
  stage: image
  dependencies:
    - build_artifact
  image: docker:26.1.0
  services:
    - docker:26.1.0-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login --username AlexLundgren --password $GITLAB_CONTAINER_REGISTRY_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/ccg-2/travelbuddy:frontend .
    - docker push registry.gitlab.com/ccg-2/travelbuddy:frontend
