stages:
  - build
  - image

build_artifact_frontend:
  stage: build
  image: node
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - frontend/dist/*

#build_artifact_backend:
#  stage: build
#  image: mcr.microsoft.com/dotnet/sdk:8.0-cbl-mariner2.0-arm64v8
#  before_script:
#    - cd backend/API
#  script:
#    - dotnet publish
#  artifacts:
#    paths:
#      - backend/API/bin/Release/net8.0/publish/*

build_image_frontend:
  stage: image
  dependencies:
    - build_artifact_frontend
  image: docker:26.1.0
  services:
    - docker:26.1.0-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_TAG: travelbuddy-frontend:$CI_COMMIT_SHORT_SHA
  before_script:
    - cd frontend
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
    - docker build -t $CI_REGISTRY/ccg-2/travelbuddy/$IMAGE_TAG .
    - docker push $CI_REGISTRY/ccg-2/travelbuddy/$IMAGE_TAG

build_image_backend:
  stage: image
  dependencies:
    - build_artifact_backend
  image: docker:26.1.0
  services:
    - docker:26.1.0-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_TAG: travelbuddy-backend:$CI_COMMIT_SHORT_SHA
  before_script:
    - cd backend/API
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
    - docker build -t $CI_REGISTRY/ccg-2/travelbuddy/$IMAGE_TAG -f Dockerfile.prod .
    - docker push $CI_REGISTRY/ccg-2/travelbuddy/$IMAGE_TAG

build_image_frontend_arm64:
  stage: image
  dependencies:
    - build_artifact_frontend
  image: docker:26.1.0
  services:
    - docker:26.1.0-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_TAG: travelbuddy-frontend-arm64:$CI_COMMIT_SHORT_SHA
  before_script:
    - cd frontend
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
    - docker build --platform linux/arm64/v8 -t $CI_REGISTRY/ccg-2/travelbuddy/$IMAGE_TAG .
    - docker push $CI_REGISTRY/ccg-2/travelbuddy/$IMAGE_TAG


#build_image_backend-arm64:
#  stage: image
#  dependencies:
#    - build_artifact_backend
#  image: docker:26.1.0
#  services:
#    - docker:26.1.0-dind
#  variables:
#    DOCKER_TLS_CERTDIR: "/certs"
#    IMAGE_TAG: travelbuddy-backend-arm64:$CI_COMMIT_SHORT_SHA
#  before_script:
#    - cd backend
#  script:
#    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
#    - docker build --platform linux/arm64/v8 -t $CI_REGISTRY/ccg-2/travelbuddy/$IMAGE_TAG .
#    - docker push $CI_REGISTRY/ccg-2/travelbuddy/$IMAGE_TAG
